name: Terraform Apply

on:
  push:
    branches:
      - main

env:
  TF_VAR_kubeconfig: /etc/rancher/k3s/k3s.yaml
  TF_VAR_downloads: ~/Downloads
  TF_VAR_qbittorrent_password: ${{ secrets.Q_PASSWORD }}
  TF_VAR_username: ${{ secrets.USERNAME }}
  TF_VAR_password: ${{ secrets.PASSWORD }}

jobs:
  terraform:
    name: Terraform Apply
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Apply
        run: |
          terraform init
          terraform apply -target=null_resource.deployment
          terraform apply
